to_do_list/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("todo.urls", namespace="todo")),
]

todo/urls.py
from django.urls import path

from todo.views import TaskListView, TaskCreateView, TagListView, TaskUpdateView, TagCreateView, TaskDeleteView, \
    TagDeleteView, TagUpdateView, complete_task

urlpatterns = [
    path("", TaskListView.as_view(), name="task-list"),
    path("tasks/create/", TaskCreateView.as_view(), name="task-create"),
    path("tasks/<int:pk>/update/", TaskUpdateView.as_view(), name="task-update"),
    path("tasks/<int:pk>/delete/", TaskDeleteView.as_view(), name="task-delete"),
    path("tags/", TagListView.as_view(), name="tags-list"),
    path("tags/create/", TagCreateView.as_view(), name="tags-create"),
    path("tags/<int:pk>/update/", TagUpdateView.as_view(), name="tag-update"),
    path("tags/<int:pk>/delete/", TagDeleteView.as_view(), name="tag-delete"),
    path('tasks/<int:pk>/complete/', complete_task, name='complete-task'),
]

app_name = "todo"

todo/models.py
from django.db import models


class Tag(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Task(models.Model):
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    deadline = models.DateTimeField(null=True, blank=True)
    is_done = models.BooleanField(default=False)
    tags = models.ManyToManyField(Tag)

    def __str__(self):
        return self.content

todo/forms.py
from django import forms

from todo.models import Task, Tag


class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = "__all__"


class TagForm(forms.ModelForm):
    class Meta:
        model = Tag
        fields = "__all__"

todo/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views import generic

from todo.forms import TaskForm, TagForm
from todo.models import Task, Tag


class TaskListView(generic.ListView):
    model = Task
    template_name = "to_do_list/index.html"
    ordering = ["is_done", "created_at"]


class TaskCreateView(generic.CreateView):
    model = Task
    form_class = TaskForm
    template_name = "to_do_list/task_form.html"
    success_url = reverse_lazy("todo:task-list")


class TaskUpdateView(generic.UpdateView):
    model = Task
    form_class = TaskForm
    template_name = "to_do_list/task_form.html"
    success_url = reverse_lazy("todo:task-list")


class TaskDeleteView(generic.DeleteView):
    model = Task
    template_name = "to_do_list/confirm_task_delete.html"
    success_url = reverse_lazy("todo:task-list")


class TagListView(generic.ListView):
    model = Tag
    template_name = "to_do_list/tags.html"


class TagCreateView(generic.CreateView):
    model = Tag
    form_class = TagForm
    template_name = "to_do_list/tag_form.html"
    success_url = reverse_lazy("todo:tags-list")


class TagUpdateView(generic.UpdateView):
    model = Tag
    form_class = TagForm
    template_name = "to_do_list/tag_form.html"
    success_url = reverse_lazy("todo:tags-list")


class TagDeleteView(generic.DeleteView):
    model = Tag
    success_url = reverse_lazy("todo:tags-list")
    template_name = "to_do_list/confirm_tag_delete.html"


def complete_task(request, pk):
    task = get_object_or_404(Task, pk=pk)
    if not task.is_done:
        task.is_done = True
        task.save()
        return redirect('todo:task-list')
    else:
        task.is_done = False
        task.save()
        return redirect('todo:task-list')

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  {% block title %}<title>To Do List</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
      integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2"
      crossorigin="anonymous">
</head>

<body>
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-2">

      {% block sidebar %}
        {% include "includes/sidebar.html" %}
      {% endblock %}

    </div>
    <div class="col-sm-10 ">

      {% block content %}{% endblock %}

    </div>
  </div>
</div>
</body>

</html>

templates/includes/sidebar.html
<ul class="sidebar-nav list-group">
  <br>

  <li class="list-group-item"><a href="{% url "todo:task-list" %}">Home</a></li>
  <li class="list-group-item"><a href="{% url "todo:tags-list" %}">Tags</a></li>
</ul>

templates/to_do_list/confirm_tag_delete.html
{% extends "base.html" %}

{% block content %}
  <div class="container" style="display: flex; align-items: center; margin-top: 200px; justify-content: center; height: 100px; flex-direction: column;">
    <h1>Are you sure you want to delete this tag?</h1>
    <div class="container" style="display: flex; align-items: center; justify-content: center; height: 100px;">
      <h3> {{ tag.name }}</h3>
    </div>
    <div class="container">
      <form action="" method="post" style="float: right; margin-right: 480px">
        {% csrf_token %}

        <br>

        <input type="submit" value="Yes" class="btn btn-danger" style="margin-right: 10px">
        <a class="btn btn-secondary" href="{% url "todo:tags-list" %}">Cancel</a>
      </form>
    </div>
  </div>
{% endblock %}

templates/to_do_list/confirm_task_delete.html
{% extends "base.html" %}

{% block content %}
  <div class="container" style="display: flex; align-items: center; margin-top: 200px; justify-content: center; height: 100px; flex-direction: column;">
    <h1>Are you sure you want to delete this task?</h1>
    <div class="container" style="display: flex; align-items: center; justify-content: center; height: 100px;">
      <h3> {{ task.content }}</h3>
    </div>
    <div class="container">
      <form action="" method="post" style="float: right; margin-right: 480px">
        {% csrf_token %}

        <br>

        <input type="submit" value="Yes" class="btn btn-danger" style="margin-right: 10px">
        <a class="btn btn-secondary" href="{% url "todo:task-list" %}">Cancel</a>
      </form>
    </div>
  </div>
{% endblock %}

templates/to_do_list/index.html
{% extends "base.html" %}
{% block title %}<title>Home</title>{% endblock %}
{% block content %}
  <div class="container" style="margin-top: 50px">
    <h1 style="text-align: center">
      TODO list
      <a href="{% url "todo:task-create" %}" class="btn btn-primary" style="float: right">Create task</a>
    </h1>

  </div>
  <br>
  <br>
  <hr>
  <div>
    {% for task in task_list %}
      <h4>
        <strong>Content:</strong> {{ task.content }}
        {% if task.is_done %}
          <h5 style="color: green"><strong style="color: #1b1b1b">Status:  </strong>Is done</h5>
          {% else %}
          <h5 style="color: red"><strong style="color: #1b1b1b">Status:  </strong>Not done</h5>
        {% endif %}
      </h4>
      <h5><strong>Created at:</strong> {{ task.created_at }}</h5>
      {% if task.deadline %}
        <h5><strong>Deadline: </strong>{{ task.deadline }}</h5>
      {% endif %}
      {% if task.is_done %}
        <div>
          <a href="{% url 'todo:complete-task' pk=task.id %}" class="btn btn-danger" style="float: right; margin-right: 50px">Task not completed</a>
        </div>

      {% else %}
        <div>
          <a href="{% url 'todo:complete-task' pk=task.id %}" class="btn btn-success" style="float: right; margin-right: 50px">Complete task</a>
        </div>

        {% csrf_token %}
      {% endif %}
      <h5><strong>Tags: </strong>{{ task.tags.all|join:", " }}</h5>
      <br>
        <div>
          <a href="{% url "todo:task-update" pk=task.id %}" style="margin-right: 10px; margin-left: 20px">Update</a>
          <a href="{% url "todo:task-delete" pk=task.id %}">Delete</a>
        </div>
      <hr>
    {% endfor %}
  </div>
{% endblock %}

templates/to_do_list/tag_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <div class="container">
    <h1>{{ object|yesno:"Update,Create" }} tag</h1>
    <div>
      <form action="" method="post" novalidate>
      {% csrf_token %}
      {{ form|crispy}}

      <input type="submit" value="Submit" class="btn btn-primary" style="float: right; margin-top: 20px">
    </div>
  </div>

{% endblock %}

templates/to_do_list/tags.html
{% extends "base.html" %}

{% block content %}
  <div class="container" style="margin-top: 50px">
  <h1 style="text-align: center">Tags List</h1>
  <hr>
    {% for tag in tag_list %}
      <table class="table table-striped">
        <td><h2>{{ tag.name }}</h2></td>
        <td><a href="{% url "todo:tag-update" pk=tag.id %}">Update</a></td>
        <td><a href="{% url "todo:tag-delete" pk=tag.id %}">Delete</a></td>
      </table>
      <hr>
    {% endfor %}
  </div>

{% endblock %}

templates/to_do_list/task_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <div class="container">
    <h1>{{ object|yesno:"Update,Create" }} task</h1>
    <div>
      <form action="" method="post" novalidate>
      {% csrf_token %}
      {{ form|crispy}}

      <input type="submit" value="Submit" class="btn btn-primary" style="float: right; margin-top: 20px">
    </div>
  </div>

{% endblock %}